- name: Installing Docker
  shell: curl -fsSL https://get.docker.com | bash
  notify: Restart Docker

- name: Adding the apt k8s keys
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding the k8s repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Installing kubeadm, kubelet, and kubectl packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
  notify: Restart Kubelet